import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header/page";
import Footer from "@/components/layout/footer";
import SessionProviderWrapper from "@/components/session-provider-wrapper";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`antialiased`}>
        <Header />
        <SessionProviderWrapper>{children}</SessionProviderWrapper>
        <Footer />
      </body>
    </html>
  );
}
